version: '3.8'

services:
  pikpak-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PIKPAK_USERNAME=your_username_here
      - PIKPAK_PASSWORD=your_password_here
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
    restart: unless-stopped